// Explicit asset paths keep brand artwork embedded in the offline HTML export.
export const technologyLogos = {
  react: { label: "React", src: "/logos/react.svg" },
  nextjs: { label: "Next.js", src: "/logos/nextjs.svg" },
  javascript: { label: "JavaScript", src: "/logos/javascript.svg" },
  typescript: { label: "TypeScript", src: "/logos/typescript.svg" },
  html5: { label: "HTML5", src: "/logos/html5.svg" },
  css3: { label: "CSS3", src: "/logos/css3.svg" },
  vite: { label: "Vite", src: "/logos/vite.svg" },
  motion: { label: "Framer Motion", src: "/logos/framer-motion.svg" },
  nodejs: { label: "Node.js", src: "/logos/nodejs.svg" },
  express: { label: "Express.js", src: "/logos/express.svg" },
  mongodb: { label: "MongoDB", src: "/logos/mongodb.svg" },
  mysql: { label: "MySQL", src: "/logos/mysql.svg" },
  flask: { label: "Flask", src: "/logos/flask.svg" },
  socketio: { label: "Socket.io", src: "/logos/socketio.svg" },
  webrtc: { label: "WebRTC", src: "/logos/webrtc.svg" },
  gemini: { label: "Google Gemini", src: "/logos/gemini.svg" },
  openai: { label: "OpenAI", src: "/logos/openai.svg" },
  tesseract: { label: "Tesseract.js", src: "/logos/tesseract.png" },
  opencv: { label: "OpenCV", src: "/logos/opencv.svg" },
  porcupine: { label: "Picovoice Porcupine SDK", src: "/logos/porcupine.png" },
  aws: { label: "AWS", src: "/logos/aws.svg" },
  docker: { label: "Docker", src: "/logos/docker.svg" },
  nginx: { label: "NGINX", src: "/logos/nginx.svg" },
  git: { label: "Git", src: "/logos/git.svg" },
  hoppscotch: { label: "Hoppscotch", src: "/logos/hoppscotch.svg" },
  copilot: { label: "GitHub Copilot", src: "/logos/copilot.svg" },
  claude: { label: "Claude Code", src: "/logos/claude.svg" },
  python: { label: "Python", src: "/logos/python.svg" },
  java: { label: "Java", src: "/logos/java.svg" },
  c: { label: "C", src: "/logos/c.svg" },
};

export const toolkitGroups = [
  {
    id: "frontend",
    label: "Frontend",
    number: "01",
    description: "The part you see. The details you feel.",
    tools: [
      ["React", "Component-driven UI", ["react"]],
      ["Next.js", "React framework", ["nextjs"]],
      [
        "JavaScript / TS",
        "Interactive experiences",
        ["javascript", "typescript"],
      ],
      ["HTML5 & CSS3", "The web foundations", ["html5", "css3"]],
      ["Vite", "Build tooling", ["vite"]],
      ["Framer Motion", "Considered motion", ["motion"]],
    ],
  },
  {
    id: "backend",
    label: "Backend",
    number: "02",
    description: "Reliable foundations behind the interface.",
    tools: [
      ["Node.js", "JavaScript runtime", ["nodejs"]],
      ["Express.js", "APIs & middleware", ["express"]],
      ["MongoDB", "Document databases", ["mongodb"]],
      ["MySQL", "Relational data", ["mysql"]],
      ["Flask", "RESTful web services", ["flask"]],
      ["Socket.io / WebRTC", "Real-time connections", ["socketio", "webrtc"]],
    ],
  },
  {
    id: "ai",
    label: "AI & automation",
    number: "03",
    description: "Making intelligence practical, one integration at a time.",
    tools: [
      ["Gemini API", "Conversational AI", ["gemini"]],
      ["OpenAI API", "AI integrations", ["openai"]],
      ["Tesseract.js", "Text extraction / OCR", ["tesseract"]],
      ["OpenCV", "Computer vision", ["opencv"]],
      ["Python / NLP", "Natural language", ["python"]],
      ["Porcupine", "Picovoice wake-word SDK", ["porcupine"]],
    ],
  },
  {
    id: "cloud",
    label: "Cloud & tools",
    number: "04",
    description: "From a local experiment to a deployed product.",
    tools: [
      ["AWS", "S3 · EC2 · CloudFront", ["aws"]],
      ["Docker", "Containerized apps", ["docker"]],
      ["Nginx", "Reverse proxy & SSL", ["nginx"]],
      ["Git", "Version control", ["git"]],
      ["Hoppscotch", "API testing", ["hoppscotch"]],
      ["AI coding tools", "Copilot · Claude Code", ["copilot", "claude"]],
    ],
  },
  {
    id: "languages",
    label: "Languages",
    number: "05",
    description: "Different languages. The same problem-solving mindset.",
    tools: [
      ["Python", "AI & automation", ["python"]],
      ["JavaScript", "The full web stack", ["javascript"]],
      ["TypeScript", "Type-safe development", ["typescript"]],
      ["Java", "Object-oriented design", ["java"]],
      ["C", "Systems fundamentals", ["c"]],
      ["SQL · MySQL", "Working with relational data", ["mysql"]],
    ],
  },
];
